---
# Inspired by Mozilla SSH recommendations
# https://infosec.mozilla.org/guidelines/openssh.html
# Fix 'sftp transfer mechanism failed' by using internal-sftp: https://github.com/ansible/ansible/issues/22127#issuecomment-328178516

- name: Harden SSH config
  become: true
  ansible.builtin.copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '600'
    backup: true
  notify:
    - Restart SSH

- name: Create file with long Diffie-Hellman moduli for SSH
  become: true
  shell: awk '$5 >= 4095' /etc/ssh/moduli > /etc/ssh/moduli.tmp
  changed_when: false

- name: Apply long moduli
  become: true
  ansible.builtin.copy:
    src: /etc/ssh/moduli.tmp
    dest: /etc/ssh/moduli
    remote_src: true
  when: not ansible_check_mode
  notify:
    - Restart SSH
