---
plugin: hetzner.hcloud.hcloud
token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35623837396438616639323563383532383135363464633033393463353336613731623765333832
          3831396136613761313336383839363437663465393864300a623130306638623434383332643532
          63366436373565646539393338653833616632383933306261393862383732376462626461353937
          3833356131356335350a643239396236366532336564346461303363633461303035646363336661
          64633136366135646531306134613161393836643661386432396234383137646337663466396332
          36366132353535303764363764356339373165363235303061663861393462373338383632653466
          66366636323037633535393337373937633962656462623166346339326139383438623435626239
          33383763643437313535

# Group VMs based on Hetzner labels
keyed_groups:
  - key: hcloud_location
    separator: ''
    prefix: hcloud_location
  - key: labels.role
    separator: ''
    prefix: ''
