---
create_vm_proxmox_image_url: https://cdimage.debian.org/cdimage/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2
create_vm_proxmox_image_storage: local
create_vm_proxmox_vm_storage: local-lvm
create_vm_proxmox_sockets: 1
create_vm_proxmox_cores: 2
create_vm_proxmox_memory_mb: 2048
create_vm_proxmox_disk_size: 20G
create_vm_proxmox_nameservers:
  - '1.1.1.1'
  - '1.0.0.1'
  - '8.8.8.8'
  - '8.8.4.4'
create_vm_proxmox_ipconfig:
  ipconfig0: 'ip=dhcp,ip6=dhcp'
create_vm_proxmox_tags: []
