---
- name: Create directories
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: '755'
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop:
    - path: "{{ stubby_config_path }}"

- name: Apply configuration
  become: true
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '644'
  loop:
    - src: stubby.yml.j2
      dest: "{{ stubby_config_path }}/stubby.yml"
    - src: docker-compose.yml.j2
      dest: "{{ dns_compose_dir }}/docker-compose.yml"
  register: _configuration_files

- name: Check if systemd-resolved is running
  become: true
  ansible.builtin.systemd_service:
    name: systemd-resolved
  register: _dns_stub_listener_active

- name: Disable systemd-resolved stub resolver
  become: true
  when: _dns_stub_listener_active.status.ActiveState == 'active'
  ansible.builtin.blockinfile:
    path: /etc/systemd/resolved.conf.d/disable-stub.conf
    state: present
    create: true
    block: |
      [Resolve]
      DNSStubListener=no
  register: _dns_stub_listener_config

- name: Restart systemd-resolved
  become: true
  ansible.builtin.service:
    name: systemd-resolved
    state: restarted
  when: _dns_stub_listener_config is changed

- name: Start DNS server
  become: true
  community.docker.docker_compose_v2:
    project_src: "{{ dns_compose_dir }}"
    state: "present"
    pull: "always"
    recreate: "{{ 'always' if _configuration_files is changed else 'auto' }}"
    remove_orphans: true
